version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - '80:80'
    depends_on:
      - client
      - admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://test" ]
      interval: 1s
      timeout: 5s
      retries: 10

  admin:
    build: ./admin
    volumes:
    - ./db:/data/db

  client:
    build: ./client
    volumes:
    - ./client/pages:/usr/src/app/pages
