version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - '3000:80'
    depends_on:
#      - client
      - admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://test" ]
      interval: 1s
      timeout: 5s
      retries: 10

  admin:
    build: ./admin

  client:
    build: ./client
